name: MCDiscord
version: '${project.version}'
main: com.emmad.mcdiscord.MCDiscord
api-version: 1.17
authors: [ EmmadUsmani ]
description: In-game commands that perform actions on a Discord server.
website: https://github.com/EmmadUsmani
commands:
  save-coord:
    description: Saves the given coordinate (or player's location) under the given name.
    usage: /<command> name [x y z]
  delete-coord:
    description: Deletes the coordinate with the given name, if the player created it.
    usage: /<command> name
  list-coords:
    description: Displays all saved coordinates.
    usage: /<command>
  get-coord:
    description: Displays the coordinate with the given name.
    usage: /<command> name
