name: MCDiscord
version: '${project.version}'
main: com.emmad.mcdiscord.MCDiscord
api-version: 1.17
authors: [ EmmadUsmani ]
description: In-game commands that perform actions on a Discord server.
website: https://github.com/EmmadUsmani
commands:
  save-coord:
    description: Saves coordinate.
